mod hardware;
mod sandbox;
mod compact;

use minisign_verify::{PublicKey, Signature};
use reqwest::blocking::Client;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::{fs, io::Write, path::{Path, PathBuf}, process::{Child, Command, Stdio}, sync::Mutex, time::Duration};
use tauri::State;

const RELEASE_API: &str = "https://api.github.com/repos/VestigeIndex/vigichain-node/releases/latest";
const RELEASE_PUBLIC_KEY: &str = "RWQItT0J/YGNHI45GYmzWqVLUP+fMp5GXIbKxjp7eH/l7vZLfhv7KUsa";
const PROVENANCE_NAME: &str = "VIGICHAIN-PROVENANCE.json";
const SBOM_NAME: &str = "SBOM.cdx.json";
const STATEMENT_TYPE: &str = "https://in-toto.io/Statement/v1";
const PREDICATE_PREFIX: &str = "https://slsa.dev/provenance/";

struct MinerProcess(Mutex<Option<Child>>);
#[derive(Debug, Deserialize)] #[serde(rename_all="camelCase")] struct MinerConfig { address:String, threads:u16, bootnodes:String, network:String, power_profile:String, cpu_limit_percent:u8, sandboxed:bool }
#[derive(Debug, Serialize)] #[serde(rename_all="camelCase")] struct NodeStatus { running:bool, pid:Option<u32>, binary_available:bool }
#[derive(Debug, Serialize)] #[serde(rename_all="camelCase")] struct SystemInfo { logical_cpus:usize, architecture:String, operating_system:String, node_binary_available:bool, node_binary_path:Option<String> }
#[derive(Debug, Deserialize)] struct GithubRelease { tag_name:String, assets:Vec<GithubAsset> }
#[derive(Debug, Deserialize)] struct GithubAsset { name:String, browser_download_url:String }
#[derive(Debug, Serialize)] #[serde(rename_all="camelCase")] struct InstallResult { tag:String, artifact:String, sha256:String, source_commit:String, builder:String, sbom_components:usize, installed_path:String, verified:bool }

fn vigi_home()->Result<PathBuf,String>{let home=std::env::var_os("HOME").or_else(||std::env::var_os("USERPROFILE")).ok_or("Unable to resolve user home directory")?;Ok(PathBuf::from(home).join(".vigichain"))}
fn node_binary_name()->Result<&'static str,String>{if std::env::consts::ARCH!="x86_64"{return Err(format!("Vigi Miner currently has no signed node artifact for architecture {}",std::env::consts::ARCH))}match std::env::consts::OS{"windows"=>Ok("vigichain-node-windows-x86_64.exe"),"linux"=>Ok("vigichain-node-linux-x86_64"),other=>Err(format!("No signed VigiChain node artifact is published for {other}"))}}
fn node_binary_path()->Result<PathBuf,String>{if let Ok(explicit)=std::env::var("VIGI_NODE_BINARY"){let p=PathBuf::from(explicit);if p.exists(){return Ok(p)}return Err("VIGI_NODE_BINARY points to a missing file".into())}let base=vigi_home()?;let canonical=base.join(node_binary_name()?);if canonical.exists(){return Ok(canonical)}let fallback=if cfg!(windows){base.join("vigichain-node.exe")}else{base.join("vigichain-node")};if fallback.exists(){return Ok(fallback)}Err("Verified VigiChain node binary not found. Install a verified release from Vigi Miner first.".into())}
fn http_client()->Result<Client,String>{Client::builder().user_agent("VigiMiner/0.3 (+https://vigichain.org)").connect_timeout(Duration::from_secs(12)).timeout(Duration::from_secs(90)).build().map_err(|e|format!("Unable to initialize secure downloader: {e}"))}
fn get_latest_release(c:&Client)->Result<GithubRelease,String>{c.get(RELEASE_API).send().map_err(|e|format!("Unable to query VigiChain releases: {e}"))?.error_for_status().map_err(|e|format!("Release API refused the request: {e}"))?.json().map_err(|e|format!("Release metadata is not valid JSON: {e}"))}
fn asset_url<'a>(r:&'a GithubRelease,n:&str)->Result<&'a str,String>{r.assets.iter().find(|a|a.name==n).map(|a|a.browser_download_url.as_str()).ok_or_else(||format!("Release {} is incomplete: missing {n}",r.tag_name))}
fn download(c:&Client,url:&str,dest:&Path)->Result<(),String>{let bytes=c.get(url).send().map_err(|e|format!("Download failed: {e}"))?.error_for_status().map_err(|e|format!("Server refused download: {e}"))?.bytes().map_err(|e|e.to_string())?;if bytes.is_empty(){return Err("Downloaded artifact is empty".into())}let mut f=fs::File::create(dest).map_err(|e|e.to_string())?;f.write_all(&bytes).map_err(|e|e.to_string())}
fn verify_signature(data:&[u8],text:&str)->Result<(),String>{let pk=PublicKey::from_base64(RELEASE_PUBLIC_KEY).map_err(|e|e.to_string())?;let sig=Signature::decode(text).map_err(|e|e.to_string())?;pk.verify(data,&sig,false).map_err(|e|format!("Release signature verification failed: {e}"))}
fn sha256_hex(data:&[u8])->String{format!("{:x}",Sha256::digest(data))}
fn verify_manifest(m:&str,a:&str,d:&str)->Result<(),String>{let matches=m.lines().filter(|line|{let mut p=line.split_whitespace();matches!(p.next(),Some(h) if h.eq_ignore_ascii_case(d))&&matches!(p.next(),Some(n) if n.trim_start_matches('*')==a)}).count();if matches!=1{return Err(format!("Signed SHA256SUMS must bind {a} exactly once"))}Ok(())}
fn parse_provenance(doc:&Value,artifact:&str,digest:&str,tag:&str)->Result<(String,String),String>{if doc.get("_type").and_then(Value::as_str)!=Some(STATEMENT_TYPE){return Err("Unexpected provenance statement type".into())}if !doc.get("predicateType").and_then(Value::as_str).unwrap_or("").starts_with(PREDICATE_PREFIX){return Err("Unexpected provenance predicate type".into())}let subjects=doc.get("subject").and_then(Value::as_array).ok_or("Provenance has no subjects")?;let mine:Vec<&Value>=subjects.iter().filter(|s|s.get("name").and_then(Value::as_str)==Some(artifact)).collect();if mine.len()!=1{return Err("Provenance subject mismatch".into())}if !mine[0].pointer("/digest/sha256").and_then(Value::as_str).unwrap_or("").eq_ignore_ascii_case(digest){return Err("Provenance digest mismatch".into())}let ext=doc.pointer("/predicate/buildDefinition/externalParameters").ok_or("Missing external parameters")?;if ext.get("ref").and_then(Value::as_str).unwrap_or("")!=format!("refs/tags/{tag}"){return Err("Provenance tag mismatch".into())}let deps=doc.pointer("/predicate/buildDefinition/resolvedDependencies").and_then(Value::as_array).ok_or("No source dependency")?;let mut commits:Vec<String>=deps.iter().filter_map(|d|d.pointer("/digest/gitCommit").and_then(Value::as_str)).map(|s|s.to_ascii_lowercase()).collect();commits.sort();commits.dedup();if commits.len()!=1||commits[0].len()!=40{return Err("Provenance must resolve one full source commit".into())}let builder=doc.pointer("/predicate/runDetails/builder/id").and_then(Value::as_str).unwrap_or("").to_string();if builder.is_empty(){return Err("Missing provenance builder".into())}Ok((commits.remove(0),builder))}
fn verify_sbom(bytes:&[u8],provenance:&Value)->Result<usize,String>{let sbom:Value=serde_json::from_slice(bytes).map_err(|e|e.to_string())?;if sbom.get("bomFormat").and_then(Value::as_str)!=Some("CycloneDX"){return Err("Dependency inventory is not CycloneDX".into())}let components=sbom.get("components").and_then(Value::as_array).ok_or("SBOM lists no components")?;if components.is_empty(){return Err("SBOM lists no components".into())}let actual=sha256_hex(bytes);if let Some(items)=provenance.pointer("/predicate/runDetails/byproducts").and_then(Value::as_array){for i in items{if i.get("name").and_then(Value::as_str)==Some(SBOM_NAME){if let Some(expected)=i.pointer("/digest/sha256").and_then(Value::as_str){if !expected.eq_ignore_ascii_case(&actual){return Err("SBOM provenance digest mismatch".into())}}}}}Ok(components.len())}

#[tauri::command] fn install_verified_node()->Result<InstallResult,String>{let client=http_client()?;let release=get_latest_release(&client)?;if !release.tag_name.ends_with("-testnet"){return Err(format!("Refusing unexpected release channel {}",release.tag_name))}let artifact=node_binary_name()?.to_string();let binary_sig=format!("{artifact}.sig");let required=[artifact.as_str(),binary_sig.as_str(),"SHA256SUMS","SHA256SUMS.sig",PROVENANCE_NAME,"VIGICHAIN-PROVENANCE.json.sig",SBOM_NAME];for n in required{asset_url(&release,n)?;}let home=vigi_home()?;fs::create_dir_all(&home).map_err(|e|e.to_string())?;let staging=home.join(format!(".install-{}-{}",release.tag_name,std::process::id()));if staging.exists(){fs::remove_dir_all(&staging).map_err(|e|e.to_string())?}fs::create_dir(&staging).map_err(|e|e.to_string())?;let result=(||{for n in required{download(&client,asset_url(&release,n)?,&staging.join(n))?}let binary=fs::read(staging.join(&artifact)).map_err(|e|e.to_string())?;verify_signature(&binary,&fs::read_to_string(staging.join(&binary_sig)).map_err(|e|e.to_string())?)?;let sums=fs::read(staging.join("SHA256SUMS")).map_err(|e|e.to_string())?;verify_signature(&sums,&fs::read_to_string(staging.join("SHA256SUMS.sig")).map_err(|e|e.to_string())?)?;let prov=fs::read(staging.join(PROVENANCE_NAME)).map_err(|e|e.to_string())?;verify_signature(&prov,&fs::read_to_string(staging.join("VIGICHAIN-PROVENANCE.json.sig")).map_err(|e|e.to_string())?)?;let digest=sha256_hex(&binary);verify_manifest(&String::from_utf8(sums).map_err(|_|"SHA256SUMS is not UTF-8")?,&artifact,&digest)?;let provenance:Value=serde_json::from_slice(&prov).map_err(|e|e.to_string())?;let(commit,builder)=parse_provenance(&provenance,&artifact,&digest,&release.tag_name)?;let sbom=fs::read(staging.join(SBOM_NAME)).map_err(|e|e.to_string())?;let count=verify_sbom(&sbom,&provenance)?;let dest=home.join(&artifact);let pending=home.join(format!(".{artifact}.verified"));fs::write(&pending,&binary).map_err(|e|e.to_string())?;#[cfg(unix)]{use std::os::unix::fs::PermissionsExt;fs::set_permissions(&pending,fs::Permissions::from_mode(0o700)).map_err(|e|e.to_string())?;}if dest.exists(){fs::remove_file(&dest).map_err(|e|e.to_string())?}fs::rename(&pending,&dest).map_err(|e|e.to_string())?;Ok(InstallResult{tag:release.tag_name.clone(),artifact:artifact.clone(),sha256:digest,source_commit:commit,builder,sbom_components:count,installed_path:dest.display().to_string(),verified:true})})();let _=fs::remove_dir_all(&staging);result}
#[tauri::command] fn system_info()->SystemInfo{let logical_cpus=std::thread::available_parallelism().map(|n|n.get()).unwrap_or(1);let binary=node_binary_path().ok();SystemInfo{logical_cpus,architecture:std::env::consts::ARCH.into(),operating_system:std::env::consts::OS.into(),node_binary_available:binary.is_some(),node_binary_path:binary.map(|p|p.display().to_string())}}
#[tauri::command] fn compact_stats(mode:String)->Result<compact::CompactStats,String>{compact::stats(&vigi_home()?,&mode)}
#[tauri::command] fn compact_now(mode:String)->Result<compact::CompactRunResult,String>{if !matches!(mode.as_str(),"automatic"|"maximum"){return Err("Compact mode must be automatic or maximum".into())}compact::compact_now(&vigi_home()?,&mode)}
#[tauri::command] fn start_mining(config:MinerConfig,process:State<'_,MinerProcess>)->Result<NodeStatus,String>{if config.network=="mainnet"{return Err("Mainnet remains locked while Core reports MAINNET_LAUNCHED=false".into())}if config.network!="testnet"||!config.address.starts_with("tvigi1"){return Err("Invalid Testnet configuration".into())}if !config.sandboxed{return Err("Vigi Miner refuses unsandboxed execution".into())}if !(10..=100).contains(&config.cpu_limit_percent)||config.threads==0{return Err("Invalid compute limit".into())}if !matches!(config.power_profile.as_str(),"eco"|"balanced"|"performance"|"custom"){return Err("Unknown power profile".into())}let available=std::thread::available_parallelism().map(|n|n.get()).unwrap_or(1);if usize::from(config.threads)>available{return Err("Requested threads exceed available CPU".into())}let mut guard=process.0.lock().map_err(|_|"Miner process lock poisoned")?;if let Some(child)=guard.as_mut(){if child.try_wait().map_err(|e|e.to_string())?.is_none(){return Ok(NodeStatus{running:true,pid:Some(child.id()),binary_available:true})}*guard=None}let paths=sandbox::prepare("testnet")?;let mut cmd=Command::new(node_binary_path()?);sandbox::apply_baseline(&mut cmd,&paths);cmd.env("VIGI_NETWORK","testnet").env("VIGI_ENABLE_MINING","true").env("VIGI_MINING_THREADS",config.threads.to_string()).env("VIGI_MINER_ADDRESS",config.address).env("VIGI_BOOTNODES",config.bootnodes).env("VIGI_POWER_PROFILE",config.power_profile).env("VIGI_CPU_LIMIT_PERCENT",config.cpu_limit_percent.to_string()).stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null());let child=cmd.spawn().map_err(|e|format!("Unable to start sandboxed node: {e}"))?;let pid=child.id();*guard=Some(child);Ok(NodeStatus{running:true,pid:Some(pid),binary_available:true})}
#[tauri::command] fn stop_mining(process:State<'_,MinerProcess>)->Result<NodeStatus,String>{let mut g=process.0.lock().map_err(|_|"Miner process lock poisoned")?;if let Some(mut c)=g.take(){c.kill().map_err(|e|e.to_string())?;let _=c.wait();}Ok(NodeStatus{running:false,pid:None,binary_available:node_binary_path().is_ok()})}
#[tauri::command] fn miner_status(process:State<'_,MinerProcess>)->Result<NodeStatus,String>{let available=node_binary_path().is_ok();let mut g=process.0.lock().map_err(|_|"Miner process lock poisoned")?;if let Some(c)=g.as_mut(){if c.try_wait().map_err(|e|e.to_string())?.is_none(){return Ok(NodeStatus{running:true,pid:Some(c.id()),binary_available:available})}*g=None}Ok(NodeStatus{running:false,pid:None,binary_available:available})}

#[cfg_attr(mobile,tauri::mobile_entry_point)] pub fn run(){tauri::Builder::default().manage(MinerProcess(Mutex::new(None))).invoke_handler(tauri::generate_handler![start_mining,stop_mining,miner_status,system_info,install_verified_node,hardware::discover_mining_hardware,compact_stats,compact_now]).run(tauri::generate_context!()).expect("error while running Vigi Miner");}
